ST_MVC_Day2/ST_MVC_Day2/Models/Office.cs
namespace ST_MVC_Day2.Models
{
    public class Office : Person
    {
        public string Location { get; set; }

        //Navigation property
        List<Employee> Employees { get; set; }
    }
}

ST_MVC_Day2/ST_MVC_Day2/Controllers/OfficeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ST_MVC_Day2.Models;

namespace ST_MVC_Day2.Controllers
{
    public class OfficeController : Controller
    {
        CompanyContext context;
        public OfficeController()
        {
            context = new CompanyContext();
        }
        public IActionResult Index()
        {
            List<Office> office = context.Offices.ToList();
            return View(office);
        }
        public IActionResult GetById(int id)
        {
            Office office = context.Offices.SingleOrDefault(e => e.ID == id);
            if (office == null)
            {
                return Content("Office not valid");
            }
            return View(office);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Office office)
        {
            try
            {
                context.Offices.Add(office);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return Content("Something went wrong");
            }
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Office office = context.Offices.SingleOrDefault(e => e.ID == id);
            ViewBag.Office = context.Offices.ToList();
            return View(office);
        }
        [HttpPost]
        public IActionResult Edit(Office office)
        {
            Office OldOfficee = context.Offices.SingleOrDefault(e => e.ID == office.ID);
            OldOfficee.Name = office.Name;
            OldOfficee.Location = office.Location;


            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            try
            {
                Office office = context.Offices.SingleOrDefault(e => e.ID == id);
                context.Offices.Remove(office);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return Content("Something went wrong");
            }
        }
    }
}

ST_MVC_Day2/ST_MVC_Day2/Views/Office/Add.cshtml
@model Office
@{
    ViewData["Title"] = "AddForm";
}

<h1 style ="color:white;" >Add Office</h1>
<form action="/Office/Add" method="post" style="color:white;">
    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Location" class="form-label"></label>
        <input asp-for="Location" class="form-control" >
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

ST_MVC_Day2/ST_MVC_Day2/Views/Office/Edit.cshtml
@model Office
@{
    ViewData["Title"] = "EditForm";
}

<h1 style="color:white;" >Edit Office Data</h1>

<form action="/Office/Edit" method="post" style="color:white;">
    <input type="number" id="ID" name="ID" value="@Model.ID" hidden />
    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" class="form-control" value="@Model.Name">
    </div>
    <div class="mb-3">
        <label asp-for="Location" class="form-label">Location</label>
        <input asp-for="Location" class="form-control" value="@Model.Location">
    </div>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

ST_MVC_Day2/ST_MVC_Day2/Views/Office/GetById.cshtml
@model Office
@{
    ViewData["Title"] = "GetById";
}

<h1 style="color:white;" >Office Information</h1>



<div style="color:black;" class="card text-center">
    <div class="card-header">
        <h1>Office Data</h1>
    </div>
    <div class="card-body">
        <h5 class="card-title">Name : @Model.Name</h5>
        <br />
        <h5 class="card-title">Location : @Model.Location</h5>
        <br />
        <a href="/Office" class="btn btn-primary">Back to list</a>
    </div>
</div>

ST_MVC_Day2/ST_MVC_Day2/Views/Office/Index.cshtml
@model List<Office>
    @{
        ViewData["Title"] = "Index";
        int i = 1;
    }

<h1 style="color:white;" >Office Data</h1>

<a href="/Office/Add" class="btn btn-success">ADD <i class="fa-solid fa-user-plus"></i></a>
    <hr />
<table class="table table-striped table-success ">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Location</th>
                <th scope="col">Controller</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@(i++)</th>
                    <td>@item.Name</td>
                    <td>@item.Location</td>
                    <td>
                    <a asp-controller="Office" asp-action="getbyid" asp-route-id="@item.ID"><i class="fa-solid fa-circle-info" style="color: #1f5131;"></i></a>
                        -
                    <a asp-controller="Office" asp-action="Edit" asp-route-id="@item.ID"><i class="fa-regular fa-pen-to-square" style="color: #1f5120;"></i></a>
                        -
                    <a asp-controller="Office" asp-action="Delete" asp-route-id="@item.ID"><i class="fa-regular fa-trash-can" style="color: #1f512b;"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>