ST_MVC_Day2/ST_MVC_Day2/Controllers/EPController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ST_MVC_Day2.Models;

namespace ST_MVC_Day2.Controllers
{
    public class EPController : Controller
    {
        CompanyContext context;
        public EPController()
        {
            context = new CompanyContext();
        }
        //get all
        public IActionResult Index()
        {
            List<EmployeeProject> employeeProject = context.EmployeeProjects.Include(e => e.Employee).Include(p => p.Project).ToList();
            return View(employeeProject);
        }

        //Getby id
        public IActionResult getbyid(int id)
        {
            EmployeeProject employeeProject = context.EmployeeProjects.Include(e => e.Employee).Include(p => p.Project).SingleOrDefault(e => e.Proj_ID == id );
            if (employeeProject == null)
            {
                return Content("Employeee not valid");
            }
            return View(employeeProject);
        }
        [HttpGet]
        public ActionResult Add()
        {
            List<Employee> employees = context.Employees.Include(e => e.EmployeeProjects).ThenInclude(p => p.Project).ToList();
            ViewBag.EmployeeProject = new SelectList(employees, "ID", "Name");
            return View(employees);
        }
        [HttpPost]
        public ActionResult Add(int id)
        {

            return RedirectToAction("index");
        }

    }
}

ST_MVC_Day2/ST_MVC_Day2/Views/EP/Add.cshtml
@{
    ViewData["Title"] = "Add";
}

@*<h1 style="color:white;">Add Project</h1>
<form action="/EP/Add" method="post" style="color:white;">
    <div class="mb-3">
        <label asp-for="@Name" class="form-label"></label>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label"></label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Password" class="form-label"></label>
        <input asp-for="Password" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Office_ID" class="form-label"></label>
        <select class="form-select" asp-for="Office_ID" asp-items="ViewBag.Office">
            <option selected>Open this select menu</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
*@

ST_MVC_Day2/ST_MVC_Day2/Views/EP/Index.cshtml
@{
    ViewData["Title"] = "Index";
    int i = 1;
}

<h1 style="color:white;">Index</h1>

<a href="/EP/Add" class="btn btn-info"> ADD <i class="fa-solid fa-user-plus"></i></a>
<hr />
<table class="table table-info table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Employee Name</th>
            <th scope="col">Project Name</th>
            <th scope="col">Working Hours</th>
            <th scope="col">Controller</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@(i++)</th>
                <td>@item.Employee.Name</td>
                <td>@item.Project.Name</td>
                <td>@item.WorkingHours</td>
                <td>
                    <a asp-controller="EP" asp-action="getbyid" asp-route-id="@item.Project.ID"><i class="fa-solid fa-circle-info"></i></a>
                    -
                    <a asp-controller="EP" asp-action="edit" asp-route-id="@item.Project.ID"><i class="fa-regular fa-pen-to-square"></i></a>
                    -
                    <a asp-controller="EP" asp-action="delete" asp-route-id="@item.Project.ID"><i class="fa-solid fa-trash-can"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

ST_MVC_Day2/ST_MVC_Day2/Views/EP/getbyid.cshtml
@model EmployeeProject
@{
    ViewData["Title"] = "getbyid";
}

<h1 style="color:white;">Projects Employee</h1>

<div style="color:black;" class="card text-center">
    <div class="card-header">
        <h1>Projects workers Data</h1>
    </div>
    <div class="card-body">
        <h5 class="card-title">Project Name: @Model.Project.Name</h5>
        <p class="card-text">Employee Name: @Model.Employee.Name</p>
        <p class="card-text">Working Hours: @Model.WorkingHours</p>
        <a href="/EP" class="btn btn-primary">Back to list</a>
    </div>
</div>